#############################################################################
# Makefile for building: libLxS.a
# Generated by qmake (2.01a) (Qt 4.7.0) on: ?? 11? 2 21:37:09 2013
# Project:  LxS.pro
# Template: lib
# Command: /usr/local/Trolltech/QtEmbedded-4.7.0-arm/bin/qmake -spec /usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/qws/linux-arm-g++ -o Makefile LxS.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -fPIC -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -fPIC -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/qws/linux-arm-g++ -I. -I/usr/local/Trolltech/QtEmbedded-4.7.0-arm/include/QtNetwork -I/usr/local/Trolltech/QtEmbedded-4.7.0-arm/include -IInclude -I. -I/usr/local/tslib/include
AR            = arm-linux-ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/QtEmbedded-4.7.0-arm/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Source/ls_log.c \
		Source/ls_list.c \
		Source/ls_common.c \
		Source/ls_uart.c \
		Source/ls_gen.c \
		Source/ls_agent.c \
		Source/ls_cli.c \
		Source/ls_tcp_server.c \
		Source/ls_modbus_client.c \
		Source/ls_udp_server.c 
OBJECTS       = ls_log.o \
		ls_list.o \
		ls_common.o \
		ls_uart.o \
		ls_gen.o \
		ls_agent.o \
		ls_cli.o \
		ls_tcp_server.o \
		ls_modbus_client.o \
		ls_udp_server.o
DIST          = /usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/staticlib.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/static.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/include_source_dir.prf \
		LxS.pro
QMAKE_TARGET  = LxS
DESTDIR       = 
TARGET        = libLxS.a

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET) 

staticlib: $(TARGET)

$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGET)
	$(AR) $(TARGET) $(OBJECTS)


Makefile: LxS.pro  /usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/qws/linux-arm-g++/qmake.conf /usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/staticlib.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/static.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/lib/libQtNetwork.prl \
		/usr/local/Trolltech/QtEmbedded-4.7.0-arm/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/qws/linux-arm-g++ -o Makefile LxS.pro
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/common/g++.conf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/common/unix.conf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/common/linux.conf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/common/qws.conf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/qconfig.pri:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/release.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/default_post.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/staticlib.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/static.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/qt.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/moc.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/resources.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/uic.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/yacc.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/lex.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/lib/libQtNetwork.prl:
/usr/local/Trolltech/QtEmbedded-4.7.0-arm/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/QtEmbedded-4.7.0-arm/mkspecs/qws/linux-arm-g++ -o Makefile LxS.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/LxS1.0.0 || $(MKDIR) .tmp/LxS1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/LxS1.0.0/ && $(COPY_FILE) --parents Include/ls_types.h Include/ls_log.h Include/ls_list.h Include/ls_common.h Include/ls_uart.h Include/ls_gen.h Include/ls_agent.h Include/ls_include.h Include/ls_cli.h Include/ls_tcp_server.h Include/ls_modbus_client.h Include/ls_udp_server.h .tmp/LxS1.0.0/ && $(COPY_FILE) --parents Source/ls_log.c Source/ls_list.c Source/ls_common.c Source/ls_uart.c Source/ls_gen.c Source/ls_agent.c Source/ls_cli.c Source/ls_tcp_server.c Source/ls_modbus_client.c Source/ls_udp_server.c .tmp/LxS1.0.0/ && (cd `dirname .tmp/LxS1.0.0` && $(TAR) LxS1.0.0.tar LxS1.0.0 && $(COMPRESS) LxS1.0.0.tar) && $(MOVE) `dirname .tmp/LxS1.0.0`/LxS1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/LxS1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

ls_log.o: Source/ls_log.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o ls_log.o Source/ls_log.c

ls_list.o: Source/ls_list.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o ls_list.o Source/ls_list.c

ls_common.o: Source/ls_common.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o ls_common.o Source/ls_common.c

ls_uart.o: Source/ls_uart.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o ls_uart.o Source/ls_uart.c

ls_gen.o: Source/ls_gen.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o ls_gen.o Source/ls_gen.c

ls_agent.o: Source/ls_agent.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o ls_agent.o Source/ls_agent.c

ls_cli.o: Source/ls_cli.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o ls_cli.o Source/ls_cli.c

ls_tcp_server.o: Source/ls_tcp_server.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o ls_tcp_server.o Source/ls_tcp_server.c

ls_modbus_client.o: Source/ls_modbus_client.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o ls_modbus_client.o Source/ls_modbus_client.c

ls_udp_server.o: Source/ls_udp_server.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o ls_udp_server.o Source/ls_udp_server.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

